# Introduction {-}

Many woody plants in (especially northern) temperate climates with seasonal weather shed their leaves in the colder months of the year. On the most recent years growth, leaves fall to reveal the twig beneath. It is these structures left behind after the leaves fall that are valuable in identification. The twig itself can vary in thickness, colour, growth pattern (straight or zig-zagged) and cross sectional shape of the twig (round, oval, square).

Where the leaf falls a scar is left behind. The distribution of leaf scars on a twig (phyllotaxy) is of major importance. The presence of at least one leaf scar indicates where the node is on a twig. Leaf scars can be present in groups of three or more, in which case they are considered whorled. Secondly leaf scars can be paired, usually on opposite sides of the twig. Thirdly and most commonly, leaf scars are present singularly at a node.Leaf scars are characteristic in size, shape and the number and distribution of vascular bundles present within them. 

Above the leaf scar, a bud will be present which contains meristems that will continue next years growth. They are often surrounded by scales, the size, shape and number of which are often diagnostic. Buds can be multiple at one node either next to each other (collateral), or above one another (superposed). The presence or absence of an *end* or *terminal* bud is determined either by the absence of an obvious leaf scar or by its morphological difference to lateral buds. Terminal buds are usually larger, if present. Sometimes buds can appear to be different even on the lateral buds and this is usually associated with a difference between buds that will go on to produce flowers, and those that will continue vegetative growth.

Twigs can have many and varied outgrowths on them. These vary from small, thin flexible outgrowths (hairs), which can be shaped simply, forked, tree-like, woolly, star-shaped and glandular to name a few. Hardened outgrowths of the stem are called *prickles*. In contrast, *spines* are modified leaves and therefore have a bud at the base of them (be careful, bud may be obscured!) and *thorns* are modified stems.

Where there is only one species in the genus, or the key specifically arrives at a species, the species is indicated in parentheses.
