Introduction

I am a strong believer in a top down approach when it comes to identification. The top down approach in this context means trying to compartmentalise hundreds of species into natural groups such as orders, families or genera. Not only does it allow you to not have to worry about species (for the moment), but it allows you to see evolutionary groups of plants more easily. When confronted with new species in other parts of the world, with luck they will be placed within your working framework.

This guide is not intended as a replacement to the guides that already exist but it can be viewed to supplement them. By its nature of only dealing with genera the keys are necessarily shorter and less complex, which is the idea of this guide. Where possible the terminology is minimised and only the major characters of use are mentioned. This key will have very little in it that is actually new, it will be a synthesis of what in the literature already exists. So for this I cannot take credit. I have relied heavily on the literature, in no particular order: Winter Botany by William Trelease (date?), The Vegetative Key to the British Flora by John Poland and Eric Clement (date?), Flora of the British Isles by Clive Stace (2012), Trees of Britain and Northern Europe by Alan Mitchell (1976), more recently Identification of trees and shrubs in winter using buds and twigs by Bernd Schulz (2018) and the Conifers Plant Crib at the BSBI (1998) by Peter Sell, http://bsbi.org/wp-content/uploads/dlm_uploads/Conifers_Crib_3.pdf. As always, where I could, terminology was simplified, though a glossary will be provided at the end.

The key to broad sections is outlined below. As this is a winter botanical key, not all species will be in leaf. First thing to note is that I have separated out the conifers first, because I believe them to have such a distinct structure compared to flowering plants that it would be confusing to integrate them with the other keys. This is not the case for deciduous coniferous species, which have been included in the main keys. This is because when there are no leaves, it is difficult to tell that a deciduous conifer is not a flowering plant. These genera are *Larix*, *Gingko*, *Metasequoia* and *Taxodium*.

Prickles are acute outgrowth of the stem, spines are modified leaves and thorns are modified stems.


The key should cater for any woody plant you find in the winter in the UK, save a few rare hortal escapes (though many of these are also covered), whether you are at the top of a mountain or by the sea.

My interest was sparked in the winter of 2016, mostly because I was frustrated I knew nothing about twigs! I have been compiling this on and off since then.

# Keys
## General Key

1. Leaves evergreen, needle like, scale like or both, usually hard, mostly resinous or odorous. Reproducing through cones -> Key 1 (Conifers)
2. Leaves evergreen, deciduous or absent, not needle or scale like, resinous or not. Reproducing (almost exclusively) through flowers and fruits -> 3 (Flowering plants) 

    3. Leaves evergreen and parallel veined -> Key 2
    4. If leaves evergreen, then not parallel veined -> 5
    
5. Leaves or leaf scars >2 per node (whorled, pseudowhorled or in bundles) -> Key 3
6. Leaves or leaf scars <3 per node -> 7

    7. Leaves or leaf scars 2 per node (opposite or subopposite) -> Key 4
    8. Leaves or leaf scars 1 per node (alternate) -> Key 5



## Key 1: Coniferous plants reproducing by cones

Conifers are seed plants without flowers, instead reproducing through cones. Only a few species are deciduous and the rest are evergreen. Most coniferous genera are highly distinct, with discrete and interesting characters. 


1. Leaves whorled. Either whorled on short shoots and needle like, 3(4)-whorled around a twig or in large distant whorls -> Key 1.1
2. Leaves not whorled -> 3
    3. Leaves needle like, in bundles of 2's, 3's or 5's -> *Pinus*
    4. If leaves needle like, not bundled -> 5
5. Leaves strictly opposite, adnate, scale like -> Key 1.2
6. Leaves alternate or spiral. Adnate, scale like or not -> 7
    7. Young twigs brown or grey (by year 2). If shoot ribbed, not green -> Key 1.3
    8. Young twigs green (until year 3). Shoot ribbed by green leaf bases -> Key 1.4


### Key 1.1: Leaves whorled




1. Leaves deciduous, cones persistent... *Larix*
2. Leaves evergreen -> 3
    3. Leaves in rosettes of 20-80 leaves on short shoots ... *Cedrus* 
    4. Leaves never on short shoots -> 5
5. Leaves many, >7, 70-120mm long in large, distant whorls ... *Sciadopitys* 
6. Leaves in 3's, rarely 4's -> 7
    7. Leaves blunt tipped ... *Fitzroya* (cupressoides)
    8. Leaves sharply pointed ... *Juniperus*


### Key 1.2: Leaves strictly opposite, scale like (Cupressaceae)

Cupressus - foliage in spray like plumes, branchlets at varying angles. Twigs rounded or 4-sided, the scale-leaves even on all sides 

x Cupressocyparis - foliage in flattened pinnate sprays, cone globular and woody. Young shoots only slightly flat, nearly 4-sided

Chamaecyparis - foliage in flattened pinnate sprays, cone globular and woody. Twigs flat, the facial scale-leaves usually flat, rarely keeled, the lateral scale-leaves keeled. Young shoots distinctly flat. Terminal shoot usually 'whip-like', drooping; cones globose, the peltate scales touching only at the
margins 

Thuja - foliage in flattened pinnate sprays, cone flask shaped, leathery. Twigs flat, the facial scale-leaves usually flat, rarely keeled, the lateral scale-leaves keeled. Young shoots distinctly flat. Terminal shoot erect; cones ovate to oblong, their scales overlapping. Foliage spreading in flat sprays, aromatic when crushed; scale-leaves a different colour on lower sides from upper 

Platycladus -foliage in flattened pinnate sprays, cone flask shaped, leathery. Foliage scentless. Twigs flat, the facial scale-leaves usually flat, rarely keeled, the lateral scale-leaves keeled. Young shoots distinctly flat. Foliage in vertical sprays, without scent when crushed; scale-leaves the same colour on both sides



1. Leaves broader, with large white patches below... *Thujopsis* (dolabrata)
2. Leaves smaller, not broad -> 3
    3. Shoots with at least some leaves in whorls of 3 (check young foliage)... *Juniperus*
    4. Leaves never 3-whorled -> 5
5. Branchlets spreading in 3 dimensions. Twigs rounded or 4-sided. Scale leaves all similar. Female cone thickly woody... *Cupressus*
6. Branchlets arranged in 1 plane, or rarely 3 dimensions. Twigs flat, or slightly flat and 4 sided. -> 7
    7. Young shoots slightly flat and nearly 4 sided. One common cultivar with branchlets in 3 dimensions... *x Cupressocyparis* (leylandii)
    8. Young shoots very flat, lateral scale leaves keeled -> 9
9. Scale leaves same colour on both sides, scentless foliage when crushed... *Platycladus* (orientalis)
10. Scale leaves lighter or whitish at margins below -> 11
    11. Female cones globular and woody, terminal shoots whip-like... *Chamaecyparis*
    12. Female cones flask shaped with scales overlapping, terminal shoots erect... *Thuja* (plicata)




Olfactory table:

Thujopsis
Juniperus - smells like gin?
Cupressus
x Cupressocyparis
Platycladus - no smell
Chamaecyparis
Thuja - sweet pineapple



### Key 1.3: Young twigs brown or grey




1. Leaves with sucker like base, attached directly to twig... *Abies*
2. Leaves without sucker like base, attached to a projection on twig -> 3
    3. Leaves with indistinct petiole, twig very rough when leaves fallen... *Picea*
    4. Leaves with obvious petiole, bare shoots slightly rough -> 5
5. Leaves minutely serrate, buds hidden by leaves... *Tsuga*
6. Leaves entire, buds prominent... *Pseudotsuga* (menziesii)





### Key 1.4: Young twigs green



1. Leaves with a petiole... *Taxus* (baccata)
2. Leaves sessile -> 3
    3. Leaves of two kinds, scale like, and linear/flat... *Sequoia* (sempervirens)
    4. Leaves all similar -> 5
5. Leaves >25mm long, >10mm wide, sharply spine tipped... *Araucaria* (araucana)
6. Leaves <25mm long -> 7
    7. Leaves spirally arranged, with free part 3-7mm... *Sequoiadendron* (giganteum)
    8. Leaves in 5 ranks, incurved, with free part 5-20mm... *Cryptomeria* (japonica)





## Key 2: Leaves evergreen, parallel veined (Asparagaceae)



1. Leaves >20cm long in rosettes at apex of stem, palm-like -> 3
2. Leaves <20cm long spirally arranged on stems ... *Ruscus* 
  3. Leaves with translucent veins ... *Cordyline* (australis)
  4. Leaves with indistinct opaque veins ... *Yucca* 



## Key 3: Leaves or leaf scars whorled




1. Leaves evergreen -> 3
2. Leaves deciduous, leaf scars apparent -> 15
    3. Leaves pseudowhorled -> 5
    4. Leaves in true whorls -> 7
5. Matted evergreen shrub < 0.4m ... *Empetrum* 
6. Tall shrub to small tree >2m ... *Rhododendron* 
    7. Leaves 3 whorled -> 9
    8. Leaves >4 whorled -> 11
9. Young twigs glandular hairy ... *Erica* 
10. Young twigs not glandular hairy -> 11
    11. Leaves > 10mm wide ... *Kalmia* 
    12. Leaves < 1mm wide ... *Erica* 
13. Leaves tough >6mm wide, strongly retrorsely scabrid ... *Rubia* 
14. Lvs ± 1mm wide ... *Erica* 
    15. Leaf scars minute, many, alternate, raised on spurs on second year shoots,
     reproductive organs cones ... *Larix* 
    16. Leaf scars larger, 3 per node, not raised -> 17
17. Twigs stout, leaf scars large with ~ 12 bundle traces in an ellipse. Buds usually arranged in two large and one small ... *Catalpa* (bignonioides)
18. Twigs slender, leaf scars smaller with 3 or fewer bundle traces -> 19
    19. Bundle trace 1, twigs mostly dead... *Fuschia*
    20. Bundle traces 3 -> 21
21. Twigs with stellate scales ... *Deutzia* (better characters?)
22. Twigs hairless or with simple hairs ... *Hydrangea* 

Add Philadelphus?

    


## Key 4: Leaves or leaf scars opposite


1. Plants scrambling, climbing or parasitic on trees -> Key 4.1
2. Plants not as above -> 3
    3. Plants evergreen -> Key 4.2
    4. Plants deciduous -> Key 4.3



### Key 4.1: Climbing, or epiphytic plants parasitic on trees



1. Plant parasitic on tree branches with twigs repeatedly forked at the nodes -> 3
2. Plant rooted in soil -> 5
    3. Twigs sickly green ... *Viscum* (album)
    4. Twigs brown ... *Loranthus* (rare hortal) 
5. Evergreen (or semi-evergreen) -> 7 
6. Deciduous -> 9
    7. Leaves simple ... *Lonicera*
    8. Leaves compound, climbing using coiling petioles ... *Clematis* 
9. Climbing by coiling petioles, persisting in winter ... *Clematis*
10. Climbing by aerial roots or scrambling -> 11
    11. Anvil shaped hairs on stems, stems twining clockwise, fruits persistent with many overlapping papery bracts ... *Humulus* (lupulus)
    12. Not as above -> 13
13. Bundle traces 1, scrambling, weakly climbing ... *Jasminum* (nudiflorum)
14. Bundle traces >1 -> 15
    15. Bundle traces 3 ... *Lonicera* 
    16. Bundle traces 5 ... *Schizophragma* (hydrangoides)




### Key 4.2: Evergreen plants


1. Leaves simple and entire -> 3
2. Leaves compound or toothed -> 5
    3. Trailing, thin, wiry shrubs <20cm tall at maturity -> Key 4.2.1
    4. Tree or upright shrub -> Key 4.2.2
5. Leaves ternate... *Choisya* (ternata)
6. Leaves toothed -> Key 4.2.3



#### Key 4.2.1: Wiring, creeping, trailing shrubs


1. Leaves with stellate hairs ... *Helianthemum*
2. Leaves with simple hairs or hairless -> 3
    3. Leaves translucent dotted with sunken glands, aromatic ... *Thymus*
    4. Leaves not translucent dotted or aromatic -> 5
5. Leaves with revolute margins -> 7
6. Leaves with flat margins -> 11
    7. Leaves < 2mm long, petiole absent ... *Calluna*
    8. Leaves >2mm long, petiole present -> 9
9. Leaves linear, rounded in cross section, 2-5mm long ... *Frankenia*
10. Leaves oblong, 5-8mm long -> *Loiseleuria*
    11. Stipules absent -> 13
    12. Stipules present ... *Herniaria*
13. *Veronica* bifurcate Linnaea here
14. *Veronica* bifurcate Linnaea here

Linnaea here?


#### Key 4.2.2: Shrubs, trees. Leaves simple.

 
1. Leaves with clear 2 pinnate translucent veins on leaves -> 3
2. Leaves with 2 pinnate veins indistinct or absent -> 19
    3. Leaves sessile -> 3
    4. Leaves petiolate -> 9
5. Leaves <1.5cm wide and with revolute margins at maturity -> 5
6. Leaves >2cm wide, with either transulcent dotted leaves or with minute glands attached to veinlets. 
    Leaf scars triangular, bundle trace 1, pith spongey and excavated (hollow) -> *Hypericum*
7. Leaves <4mm wide, rosemary scented. Bundle traces 3 ... *Rosmarinus*
8. Leaves >4mm wide (on average), odourless. Bundle traces in a transverse line ... *Kalmia*
    9. Leaves >2cm long -> 11
    10. Leaves <2cm long ... *Lonicera* (leaves <2cm long? Really?)
11. Leaves with dendritic hairs ... *Phlomis*
12. Leaves with hairs simple or absent -> 13
    13. Leaves with dense silver silky hairs below ... *Olearia* (GARRYA? LEAVES GREY WOOLLY BELOW AND UNDULATE LEAF MARGINS?)
    14. Leaves hairless both sides, except for vein axils below -> 15
15. Vein axils below with tufts of hairs ... *Viburnum*
16. Leaves glabrous -> 17
    17. Sipules present, fused between petiole bases, young twigs ± square ... *Coprosma*
    18. Stipules absent, young twigs rounded, at most angled slightly below the nodes ... *Ligustrum*
19. Leaves white hairy at least below, strongly aromatic -> 21
20. Leaves never white hairy, aromatic or not -> 23
    21. Leaves hairy with long stellate hairs both sides, lavendar scented ... *Lavandula*
    22. Leaves glabrous above, rosemary scented ... *Rosmarinus*
23. Twigs square, leaves odorous -> 25
24. Twigs round, leaves odourless -> 29
    25. Leaves gland pitted one or either side -> 25
    26. Leaves not gland pitted -> *Buxus*
27. Young twigs green, minutely ciliate, menthol scented ... *Hyssopus*
28. Young twigs whitish, leaves long ciliate at base, sage scented ... *Satureja*
    29. Leaves strongly revolute, <2mm long, sessile ... *Calluna*
    30. Leaves not revolute -> 31
31. Leaves fleshy, mealy grey <6cm, not valvate when developing ... *Atriplex*
32. Leaves not fleshy, valvate when developing ...  *Veronica* (sect Hebe)



#### Key 4.2.3: Shrubs, trees. Leaves toothed.

 
1. Twigs with dendritic hairs ... *Phlomis*
2. Twigs never with dendritic hairs -> 3
    3. Twigs with stellate hairs -> 5
    4. Twigs without stellate hairs -> 7
5. Stipules present, leaves white felted below ... *Buddleja*
6. Stipules absent, leaves stellate hairy below ... *Viburnum*
    7. Leaves < 2cm long, stems creeping and prostrate ... *Linnaea*
    8. Leaves >2cm long, stems never creeping -> 9
9. Petiole with 1 vascular bundle -> 11
10. Petiole with 3 vascular bundles -> 13
    11. Twigs square ... *Phygelius*
    12. Twigs round -> 15 
13. Not net veined, weak 2 pinnate veins. Leaves with yellow blotches above, petiole green ... *Aucuba*
14. Net veined and strongly 3-pli-veined. No yellow blotches, petiole reddish ... *Viburnum*
    15. Young twigs brown, each leaf tooth with a fragile claw like gland ... *Euonymus*
    16. Young twigs green, leaf teeth without glands -> 17
17. Leaves cuneate at base, buds with scales ... *Rhamnus*
18. Leaves rounded at base, buds naked ... *Phillyrea* 


Evergreen:

TOOTHED LVS
Aucuba - bt's 3, pith chambered with granular septa, scars slightly raised, large and crescent shaped

Buddleja - stems 4 ridged, pith large, white and continuous, scars half round or triangular, small, bt 1. Stipule scars transversely connected
Viburnum - bt's 3 or in groups of 3 with the middle bundles 2, pith continuous, leaf scars crescent shaped or angular v shaped
Linnaea - leaf scars raised and shrivelled, single bt obscured
Euonymus - scars small, elevated, bt 1 towards the top of the scar
Phygelius - twigs square
Rhamnus - pith rounded continuous and white, bt's 3 or in a transverse series, buds with scales
Phillyrea - bt 1, scars crescent shaped

LVS TERNATE
Choisya - !
ENTIRE LVS
  Phlomis - 
  Coprosma - 
  Buxus - bt 1, leaf scars minute and crescent shaped, pith minute and cont. Twigs flat grooved between each pair of leaves
  Olearia
  Kalmia - bt's in a transverse line, scars half round or shield shaped, pith small and cont
  Calluna - scars opposite, minute, crescent shaped, bt 1, pith round cont
  Hebe - 
  Viburnum - bt's 3 or in groups of 3 with the middle bundles 2, pith continuous, leaf scars crescent shaped or angular v shaped
  Ligustrum - pith moderate, white and homogenous, scars crescent shaped with bt 1
  Lavandula - 
  Rosmarinus - twigs 4 sided, leaf scars deeply u shaped, bt's 3 
  Hypericum - leaf scars triangular, 1 bt, pith spongey and finally excavated
 ?? Garrya - bt's 3, pith continuous, scars angularly u-shaped 
 
??
Hyssopus
Satureja
??
Atriplex

??
Helianthemum
Thymus
Loiseleuria
Frankenia
Herniaria
Fuschia
Weigela
Kolkwitzia
Phygelius
Phillyrea
??
Akebia




### Key 4.3: Deciduous plants




1. Bundle trace 1 -> Key 4.3.1
2. Bundle traces >1 -> 5
    3. Bundle traces 3 -> Key 4.3.2
    4. Bundle traces >3 -> Key 4.3.3



#### Key 4.3.1: Bundle trace 1



1. Twigs green ... *Euonymus*
2. Twigs not green when mature -> 3
    3. Trees -> 5
    4. Shrubs -> 9
5. Terminal buds always present, buds felted brown, grey or black ... *Fraxinus*
6. Terminal buds absent -> 11
    7. Pith chambered, twigs densly hairy ... *Paulownia* (tomentosa)
    8. Pith solid, twigs red brown... *Metasequoia* (glyptostryboides)
9. Buds sometimes whorled in 3's... *Fuschia*
10. Buds strictly opposite -> 11
    11. Pith present, solid, whitish -> 13
    12. Twigs hollow or chambered, brownish -> 15
13. Buds mostly in pairs at twig apices, glandular ciliate with 6-7 scales ... *Syringa*
14. Buds singular at twig apices, ciliate with ± 4 pairs of opposite scales ... *Ligustrum*
    15. Buds >11 pairs of scales, twigs chambered to hollow between nodes ... *Forsythia*
    16. Buds <4 pairs of scales, or absent, twigs hollow but never chambered -> 17
17. Leaf scars mostly torn, partly connected by transverse ridges, buds with keeled scales. Fruits white or red berries ... *Symphoricarpos*
18. Leaf scars never torn, triangularly lens shaped, not partly connected by ridges, buds without scales ... *Hypericum*
    


#### Key 4.3.2: Bundle traces 3



1. Transverse ridge not present between buds or leaf scars -> 3
2. Transverse ridge present between buds or leaf scars, or leaf scars abut -> 7
    3. Shoots thorny, buds with 8-10 dark brown scales, terminal buds present... *Rhamnus* (cathartica)
    4. Shoots not thorny, buds red with one scale visible, terminal buds absent... *Cercidiphyllum* (japonicum)
5. Buds hidden behind leaf scar (which is like a thin membrane)... *Philadelphus* 
6. Buds exposed and obvious -> 7
    7. Buds naked -> 9
    8. Buds with scales -> 13
9. Only terminal bud naked, twigs stout... *Hydrangea*
10. All buds naked -> 11
    11. Twigs but especially buds with stellate hairs... *Viburnum*
    12. Twigs and buds without stellate hairs but with medifixed hairs... *Cornus*
13. Stipule scars large and obvious... *Staphylea* 
14. Stipule scars absent or not obvious -> 15
    15. Buds with a pair of scales fused, enveloping bud, buds globose, red. Or flowering in winter, fragrant... *Viburnum* 
    16. Bud scales >2, not fused, not flowering in winter -> 17
17. Pith hollow between nodes -> 19
18. Pith solid, or spongey -> 23
    19. Buds solitary, twigs green ... *Leycesteria*
    20. Buds often superposed or collateral, twigs never green -> 21
21. Buds >3mm long, with buds often superposed... *Lonicera*
22. Buds <3mm long, buds often collateral... *Symphoricarpos*
    23. Twigs with 2-4 ridges decurrent from nodes. 2-valved capsules persistent ... *Weigela* 
    24. Twigs without ridges decurrent from nodes, fruits rarely persistent -> 25
25. Bundle traces forming a line, fruits persistent, bristly with 5 lobed calyx...*Kolkwitzia*
26. Bundle traces distinct, fruits not persistent, or if they are, not as above -> 27
    27. Pith spongey, twigs stout... *Sambucus*
    28. Pith solid, twigs more slender... *Acer*



#### Key 4.3.3: Bundle traces >3


1. Leaf bases obscuring leaf scars -> 3
2. Leaf scars clearly present -> 5
    3. Twigs green, hollow... *Leycesteria* (formosana)
    4. Twigs red or purplish, solid... *Acer* (section Palmata)
5. At least some nodes in whorls of 3 -> 7
6. Nodes strictly opposite -> 11
    7. Bundle traces >8 in an ellipse or horseshoe shape, terminal bud absent -> 9
    8. Bundle traces < 7 (usually 3-5), terminal bud present... *Hydrangea*
9. Each node with one small leaf scar, and two large... *Catalpa* (bignonioides)
10. Leaf scars all the same size... *Clerodendron* (trichotomum)
    11. Large stipule scars between leaf scars... *Staphylea* (pinnata)
    12. If stipule scars present, inconspicuous -> 13
13. Trees -> 15
14. Shrubs -> 21
    15. Terminal bud present, pith solid -> 17
    16. Terminal bud absent, pith chambered... *Paulownia* (tomentosa)
17. Bundle traces many in a closed circle, buds furry... *Fraxinus*
18. Bundle traces <9, distinct, buds not furry but may be hairy -> 19
    19. Terminal buds >15mm, leaf scars large, shield shaped... *Aesculus*
    20. Terminal buds < 15mm, leaf scars smaller, mostly crescent shaped... *Acer*
21. Terminal bud very large (15-20mm), naked... *Hydrangea*
22. Terminal bud smaller <15mm, often absent from shoots -> 23
    23. Pith wide, spongey, twigs stout ... *Sambucus* 
    24. Pith narrower, hard, more slender ... *Acer* 
    


Deciduous:

Fuschia
Weigela
Kolkwitzia

    Clerodendron - twigs obscurely 4 sided, pith large round white and continuous, buds superposed but lower often obscured by leaf scar, round ovoid. Leaf scars sometimes in whorls of three, elliptical, bt's 9 or aggregated in a U shaped series (?). No interpetiolar ridge.

-- Clerodendron trichotomum

    Paulownia - twigs stout, compressed at nodes. Pith large and chambered or hollowed between nodes. Buds superposed and sessile with 4 exposed blunt scales. Scars elliptical and more or less notched at the top. Bt's many in a near closed elliptical series. Without interpetiolar ridge.

QA - Paulownia tomentosa

    Rhamnus - pith rounded, continuous and white, scars small or more or less raised, bt's 3 or in a transverse series, buds small sessile (naked or scaled). No interpetiolar ridge

OB - Rhamnus alaternus

    Aesculus - pith large, 6 sided, pale. Upper most buds very large, half dozen exposed scales. leaf scars shield shaped or triangular, bundle traces 3 or in three groups. Weakly ridged between buds

RG - Aesculus hippocastanum
RG - Aesculus carnea
RG - Aesculus indica

          Sambucus - twigs (6)8-10 sided, pith large, soft and continuous, buds with 3-5 pairs of scales, end bud mostly lacking. Scars crescent shaped, 3-4 sided large and transversely connected. Bundle traces 3,5,7. Interpetiolar ridge present

SJ - ebulus
SC - nigra
SC - racemosa

    Fraxinus - twigs stout, stiff, squarish and compressed at nodes. Buds sessile, superposed, 2-3 pairs of opposite scales, those of end bud often lobed. Bt's in a u-shaped series. Scars half round and broadly u shaped. Without interpetiolar ridge.

SC - excelsior
SC - angustifolium
SC - ornus

    Viburnum (lantana, opulus) - twigs more or less 6 sided, pith round to 6 sided, continuous. End bud naked and stellate scurfy (lantana) or scaled and stalked ovoid (opulus). Scars crescent shaped, bt's 3

QA - opulus (interpetiolar ridge)
OA - lantana (interpetiolar ridge)


Leycesteria -  soft wooded shrubs, twigs slender and round and pith excavated. Buds with 1-2 pairs of exposed scales, the outer attenuate. Leaf scars raised and minute so as to equal bud. Opposite scars connect in a cross line. Bt's 3. With interpetiolar ridge

OA/LA - formosana

    Cornus - twigs often bright coloured, round to 6 sided, pith white, continuous or soft or spongey. Buds stalked, oblong with a pair of valvate scales. Leaf scars raised and crescent shaped (raised on first winter on petiole bases). Bt's 3, leaf scars transversely joined. With interpetiolar ridge weak/absent

LA - koenigii
LA - mas
LA - sanguinea
LA - sericea


    Deutzia -  twigs stellate pubescent, pith round, pale and spongey or brown and excavated between nodes (in our species yes). Buds with 2-6 pairs of scales. Scars triangular or transversely elongated and connected by transverse ridges. With interpetiolar ridge

OA - scabra

  Philadelphus - twigs lined to hexagonal, buds with 2 valvate and hairy scales. Leaf scars half round with a thin membrane that covers the bud or crescent shaped when this is burst, connected transversely. Bt's 3. With interpetiolar ridge

OA - coronarius
OA - microphyllus

Acer - twigs terete to six sided, pith round continuous and pale, buds with 2 to several pairs of scales, leaf scars U shaped bundle traces 3, 5, 7, 9


QA - campestre
QA - cappadocicum
RG/SC - negundo
QA - platanoides
QA - pseudoplatanus
QA - saccharum

Lonicera - twigs rounded, slender, bt's 3. With interpetiolar ridge

LA - xylosteum
LA - maackii
LA - formosa
LA - x purpusii
LA - tatarica

Hydrangea - pith large, continuous and pale, buds with 4-6 exposed scales, leaf scars crescent shaped, with connecting crossline. Bt's 3. With interpetiolar ridge

OA - macrophylla

*Euonymus - twigs characteristically green, pith round to 4 angled, greenish and spongey. Buds with 3-5 pairs of at first serrulate scales, scars small, half elliptical, somewhat elevated. Bt 1, transverse towards the top of the scar. No interpetiolar ridge.

OB - latifolius
OB - europaeus


*Ligustrum - twigs rounded to 4 lined below the nodes, pith moderate white and homogenous, buds with 2-3 exposed scales. Leaf scars crescent shaped, raised and small. Bt 1. No interpetiolar ridge

LB - vulgare
LB - ovalifolium (mostly evergreen)

*Forsythia - pith chambered to excavated, twigs moderately 4 sided. Buds with a dozen pairs of scales. Leaf scars shield shaped, small. Bt 1. No interpetiolar ridge

OB - x intermedia

*Symphoricarpos - small deciduous shrubs. Pith brownish, usually excavated, buds with about 3 pairs of keeled scales. Leaf scars small and mostly torn, raised and partly connected by transverse ridges, bt 1

LA - albus 
LA -orbiculatus
LA - x chenaultii


*Hypericum - twigs angled at least below the nodes, pith brown, spongey and finally excavated. Buds with 2 or several scarcely specialised scales. Scars triangularly lens shaped, bt 1
*Syringa - twigs moderate to slender, pith homogenous, buds with around 4 pairs of scales. Scars crescent or shield shaped. Bt 1 transverse and compound. No interpetiolar ridge.

LB - vulgaris

          Staphylea - twigs moderate and rounded, glabrous. Pith large, continuous. Buds ovoid, glabrous 2 edged. Scars crescent shaped. Bt's 5 or 7. Stipule scars half round or elongated. With interpetiolar ridge.





## Key 5: Leaves or leaf scars alternate

1. Plants scrambling or climbing -> Key 5.1
2. Plants not as above -> 3
    3. Plants evergreen -> Key 5.2
    4. Plants deciduous -> Key 5.3





### Key 5.1: Plants scrambling or climbing


1. Plant with leaf opposed tendrils -> 3
2. Plant without tendrils -> 5
    3. Tendrils simple or forked and never thickened into pads, no lenticels on twigs, buds smaller, subglobose ... *Vitis*
    4. Tendrils branched 2 or more times and often thickened into pads, lenticels on twigs, buds larger, round conical ... *Parthenocissus*
5. Leaves evergreen -> 7
6. Leaves deciduous -> 9
    7. Stems with adventitious aerial roots, leaves lobed... *Hedera*
    8. Without aerial adventitious roots, leaves almost always entire... *Muehlenbeckia*
9. Stipule (ochreae) scars encircling twigs, at least in older twigs... *Fallopia*
10. Stipule scars absent -> 11
    11. Buds absent... *Salpichroa* (rare)
    12. Buds present -> 13
13. Buds superposed (one above another)... *Aristolochia*
14. Buds single at nodes -> 15
    15. Bundle trace 1, buds with << 12 scales -> 17
    16. Bundle traces 6 or 3 at level of stem, buds with ~12 mucronate scales... *Akebia*
17. Twigs pale, inconspicuously 5 ridged, hard wooded scrambling shrub, sometimes spiny... *Lycium*
18. Twigs darker, rounded, soft wooded twiner, never spiny. Frequently with dried berries in panicles... *Solanum*



### Key 5.2: Evergreen plants


1. Leaves simple -> 3
2. Leaves compound -> Key 5.2.1
    3. Leaves entire -> Key 5.2.2
    4. Leaves toothed or lobed -> Key 5.2.3


#### Key 5.2.1: Leaves compound



1. Leaflets with spiny margins... *Mahonia*
2. Leaflets without spiny margins -> 3
    3. Leaves 1-pinnate... *Coronilla*
    4. Leaves > 1 pinnate... *Acacia*






#### Key 5.2.2: Leaves entire


1. Tree or tall shrub >1.2m -> 3
2. Low growing shrub <1.2m, prostrate, erect or mat forming -> 35
    3. Leaves with peltate scales or stellate hairs -> 5
    4. Leaves without peltate scales or stellate hairs -> 9
5. Peltate scales present -> 7
6. Peltate scales absent, stellate hairs present. Leaves spine tipped when young -> *Quercus* 
    7. Leaves strongly net veined... *Olearia*
    8. Leaves not strongly net veined...*Eleagnus*
9. Stipules modified into spines (in leaf axils), wood yellow underneath... *Berberis*
10. Spines not present -> 11
    11. Leaves white felted or woolly beneath -> 13
    12. Leaves never white felted -> 15
13. Leaves white felted, buds naked... *Brachyglottis*
14. Leaves short woolly below, bud with several scales... *Pittosporum*
    15. Petiole with sheathing base on stem, twigs yellowish green... *Griselinia*
    16. Petiole never sheathing, twigs green or brown -> 17
17. Twigs and leaves with almond odour when crushed... *Photinia*
18. Not with an almond odour -> 19
    19. Leaves bay scented... *Laurus*
    20. Leaves not bay scented -> 21
21. Leaves dotted with translucent glands... *Skimmia*
22. Leaves never with translucent glands -> 23
    23. Leaves sessile... *Bupleurum*
    24. Petiole present -> 25
25. Leaves spine tipped at apex... *Ilex*
26. Leaves never spine tipped -> 27
    27. Leaves sivery due to crystalline cells on both sides... *Atriplex*
    28. Leaves never silvery -> 29
29. Twigs hairless -> 31
30. Twigs hairy (look closely) -> 33
   31. Leaves much larger > 8cm long... *Rhododendron*
   32. Leaves smaller < 7cm... *Pittosporum*
33. Leaves in pseudowhorls at twig apex leading to bunched leaf scars from last years growth, twig hairs not S-shaped at base. Stipules absent... *Pittosporum*
34. Leaves never in pseudowhorls, twig hairs S-shaped at base, stipules present and soon falling... *Cotoneaster*
    35 (2). Leaves revolute at least when young, often strongly revolute at maturity -> 37
    36. Leaves with flat margins, not revolute when young -> 47
37. Leaves hairless -> 39
38. Leaves hairy -> 45
    39. Leaves strongly revolute, cylindrical, glandular ciliate only when young ... *Empetrum*
    40. Leaves weakly revolute -> 41
41. Leaves gland dotted below... *Vaccinium*
42. Leaves not gland dotted below -> 43
    43. Stems >1mm diameter, not rooting at nodes... *Andromeda*
    44. Stems <1mm diameter, rooting at nodes... *Vaccinium*
45. Leaves orange woolly below... *Rhododendron* (subgenus Ledum)
46. Leaves white woolly below... *Daboecia*
    47. Stipules or stipule scars present... *Cotoneaster* (Herniaria keys out here if evergreen, but apparently alternate leaved due to one leaf smaller or aborted)
    48. Stipules absent -> 49
49. Leaves fleshy -> 51
50. Leaves not fleshy -> 55
    51. Leaves cylindrical, or nearly so -> 53
    52. Leaves flat, green... *Sedum*
53. Leaves glaucous... *Suaeda*
54. Leaves green... *Artemisia*
    55. Leaves ± linear... *Iberis*
    56. Leaves more obovate -> 57
57. Leaves >5cm... *Daphne*
58. Leaves <3cm -> 59
    59. Leaves strongly net veined... *Arctostaphylos*
    60. Leaves not net veined, very rare... *Diapensia*



 
#### Key 5.2.3: Leaves toothed or lobed



1. Leaves toothed -> 3 
2. Leaves lobed -> 39
    3. Branches spiny or thorny -> 5
    4. Branches unarmed -> 7
5. Spines at stem nodes, leaves spine toothed... *Berberis*
6. Spines at ends of branches, leaves not spine toothed... *Pyracantha* (coccinea)
  7. Low shrub < 60cm tall -> 9
  8. Large shrub or tree -> 17
9. Leaves strongly net veined -> 11
10. Leaves not net veined -> 13
    11. Leaves <3cm long, white woolly below, buds without scales... *Dryas* (octopetala)
    12. Leaves >5cm long, not white woolly below, buds with scales... *Gaultheria* (shallon)
13. Leaves gland pitted below... *Vaccinium* (vitis-idaea)
14. Leaves not gland pitted below -> 15
    15. Leaves few and clustered at stem apices... *Gaultheria* (procumbens)
    16. Leaves many and distributed along stems... *Phyllodoce* (caerulea)
17. Plant with peltate scales... *Eleagnus* (macrophylla)
18. Without peltate scales -> 19
    19. Plant with stellate hairs, buds clustered at leaf apices... *Quercus*
    20. Plant without stellate hairs -> 21
21. Leaves white hairy below -> 23
22. Leaves not white hairy below -> 25
    23. Young twigs white felted... *Brachyglottis* (x jubar)
    24. Young twigs brown... *Olearia* (macrodonta)
25. Leaves at least at apex, spiny -> 27
26. Leaves not spiny -> 29
    27. Twigs green, leaves >3cm, tree... *Ilex*
    28. Twigs reddish, leaves <3cm, shrub... *Gaultheria*
29. (Young) twigs with glandular hairs or reddish bristly hairs -> 31
30. (Young) twigs not glandular hairy or bristly -> 35
    31. Leaves aromatic with glands below... *Escallonia* (macrantha)
    32. Leaves not aromatic, no glands below -> 33
33. Tall shrub to 5m, leaves cuneate at base... *Arbutus* (unedo)
34. Shrub to 1.5m, leaves rounded to cordate at base... *Gaultheria* (shallon)
    35. Young twigs hairy -> 37
    36. Young twigs hairless... *Prunus*
37. Leaves <5m long... *Rhamnus* (alaternus) 
38. Leaves >7cm long... *Leucothoe* (fontanesia)
    39 (2). Leaves with stellate hairs -> 41
    40. Leaves with simple hairs, or hairless -> 43
41. Stellate hairs both sides... *Lavatera*
42. Stellate hairs below only... *Quercus*
    43. Leaves >90cm, divided to base in 30-40 lobes, in terminal crown, trunk covered in petiole bases. Palm... *Trachycarpus* (fortunei)
    44. Leaves <10cm, not as above -> 45
45. Leaves white woolly on one or both sides -> 47
46. Leaves not woolly or velvety, leaves to 25cm, palmately lobed... *Fatsia* (japonica)
    47. Leaves white woolly all over, pinnately lobed, aromatic. Plant not rooting at nodes... *Santolina* (chamaecyparissus)
    48. Leaves white woolly below only -> 49
49. Leaves to 12cm, ovate, with translucent dots... *Rubus* (tricolor)
50. Leaves <2cm, oblong, no translucent dots... *Dryas* (octopetala)
    

    
    
### Key 5.3: Deciduous plants


1. Twigs with spines, prickles or thorns -> Key 5.3.1
2. Twigs unarmed -> 3
    3. Buds with bud scales -> 5
    4. Buds without bud scales, or buds hidden/obscured -> Key 5.3.2
5. Leaf scars with 3 bundle traces, or in 3 distinct groups -> 7
6. Leaf scars not with 3 bundle traces, or leaf scars and bundle traces obscured/absent -> 9
    7. Terminal buds present -> Key 5.3.3
    8. Terminal buds absent -> Key 5.3.4
9. Terminal buds present -> Key 5.3.5
10. Terminal buds absent -> Key 5.3.6


    
    
#### Key 5.3.1: Twigs with spines, prickles or thorns

1. Plant with prickles or spines -> 3
2. Plant with thorns -> 13
    3. Plants with spines, occurring beneath each bud at each node -> 5
    4. Plants without spines, but with prickles on stems -> 9
5. 1 or 3(+) spines at each node -> 7
6. 2 spines at each node, flattened lengthwise and buds concealed beneath leaf scar... *Robinia*
    7. Leaf scars many on short shoots beneath bud, wood bright yellow beneath... *Berberis*
    8. Leaf scars singular and distinct above spines... *Ribes* (uva-crispa)
9. Twigs extremely stout, leaf scars half encircling twig with ~15 bundle traces in a line... *Aralia* (elata)
10. Not as above, bundle traces 3, if visible -> 11
    11. Plant with persistant petiole base, where leaf has torn off... *Rubus*
    12. Leaf scars present, almost linear... *Rosa*
13 (2). Twigs with peltate scales -> 15
14. Twigs never with peltate scales -> 17
    15. Twigs without terminal buds, grey to bronze brown scales... *Hippophae* (rhamnoides)
    16. Twigs with terminal buds (in at least some twigs), olive brown to silver scales... *Eleagnus* (umbellatus)
17. Twigs never with terminal buds -> 19
18. Twigs with terminal buds -> 21
    19. Buds mostly lateral to thorns... *Chaenomeles* 
    20. Buds, often many, on thorns themselves. (something about collateral buds?)... *Prunus* (spinosa)
[[21. Thorns not very sharp... *Malus*
22. Thorns sharp -> 23
    23. Twigs densly long, patent hairy... *Mespilus* (germanica)
    24. Twigs not hairy or adpressed hairy -> 25
25. Buds purplish, acute... *Pyrus*
26. Buds rounded, reddish... *Crataegus*]] IMPROVE. FIND BUDS.



#### Key 5.3.2: Buds without bud scales, or buds hidden.

		Buds without bud scales, or buds at least partly obscured
			With terminal buds
				LABURNUM
				RHAMNUS (FRANGULA)
				PARROTIA 
				PTEROCARYA
				JUGLANS

			Without terminal buds
				RHUS - leaf scar small and almost encircling bud. Buds with long hairs, blunt conical. Twigs hairy and with milky sap. Pith ochre yellow. Bundle traces 3.
				ROBINIA - leaf scar large, buds covered initially by a membrane, twigs angled. Bundle traces 3.
				BUDDLEJA (ALTERNIFOLIA) - deciduous, soft wooded shrubs, stems 4 ridged. Twigs almost hairless, but with some stellate hairs (and buds). 1 pair of exposed scales. Bundle trace 1.
				COTONEASTER - shrubs to small trees, twigs rounded. Pith continuous. Bundle trace 1, indistinct, stipules mostly persistent
				SPARTIUM - twigs green, elongated, striate ridged. Pith continuous. Buds shorter than elongated leaf cushion. Leaf scars minute and bundle trace 1.
				GENISTA? - twigs green, ribbed or grooved. Pith continuous. Buds small, solitary, sessile and ovoid ~6 scales. BT 1.
				CYTISUS - twigs green, terete, ribbed or grooved. Pith continuous. Buds small with ~4 scales, often hidden behind leaf scars. Bundle traces 1. Stipules or stipule scars at the top of the leaf cushion.



1. Terminal buds present -> 3 
2. Terminal buds absent -> 11
3. Pith chambered -> 5
4. Pith continuous -> 7 
    5. Terminal bud leaves spreading, >15mm long... *Pterocarya* (fraxinifolia)
    6. Terminal bud leaves compact, <15mm long... *Juglans* 
7. Twigs with at least some stellate hairs, buds dark brown... *Parrotia* (persica)
8. Twigs never with stellate hairs -> 9
    9. Stipules persistent on large leaf cushions, buds silvery hairy... *Laburnum* 
    10. Stipules minute, if present, buds densely brown hairy...*Rhamnus* (frangula)

11 (2). Buds obscured, either by remains of leaf bases or by a membrane -> 13
12. Buds entirely unobscured -> 19
    13. Buds obscured by a membrane, later splitting. Bundle traces 3... *Robinia* (pseudo-acacia)
    14. Buds obscured by leaf bases, bundle trace 1 -> 15
15. Twigs finely striated, rush like... *Spartium* (junceum)
16. Twigs angled winged, or grooved -> 17
    17. Twigs 5 angled or winged... *Cytisus*
    18. Twigs furrowed with >5 angles, the slender twigs 4 angled... *Genista* (CHECK)
19. Stems 4 ridged, with some stellate hairs... *Buddleja*
20. Stems not 4 ridged -> 21
    21. Leaf scar almost encircling the bud. Stipules absent. Twigs very hairy with milky sap. Bundle traces 3... *Rhus*
    22. Leaf scar tiny, not encircling bud. Stipules mostly persistent. Twigs hairy or not, no sap. Bundle trace 1... *Cotoneaster*



#### Key 5.3.3: Leaf scars with 3 bundle traces, terminal buds present.
(buds), (leaf scars), (twigs)

	With three bundle traces
		Buds with bud scales
			With terminal buds
			JUGLANS - lateral buds often superposed, blunt to acute with broad. Bud scales thin and scaly, rounded at tip. Leaf scars large and as broad as twig, often ± 3 lobed, with 3 groups of semi circular traces. Twigs thick, slightly angular, hairless.
			ALNUS - lateral buds spiral in 1/3 divergence. First bud scale turned towards the stem (adaxial). Buds stalked. Number and shape of bundle traces variable and leaf scars too. Twigs and pith often 3 angular. Infructescences are persistent and cone like.
			BETULA - only short shoots with terminal buds, with 5-8 scales on lateral short shoots and 3-5 scales on lateral buds.
			STACHYURUS - buds dimorphic. inflorescence branches well developed in racemes. Terminal buds ~3mm long, laterals 2mm. 2-3 outer bud scales. Leaf scars with 3 traces, central larger, laterals less distinct. Twigs slender, glabrous, red to olive brown, long and curving down.
			PRUNUS - usually ~6 exposed scales, buds collaterally multiple, elongated ovoid or conical. Terminal buds present (cherries, almonds, peaches) or absent (apricots,plums and sloes). Bundle traces 3, minute, scars half round, elliptical. Pith pale or brown, solid. May have to key out last...
			RIBES - buds scales spiral , simple, rather loose, acute, short stalked. Bark shedding. Leaf scars u shaped or broadly crescent shaped. Twigs solid to spongey, decurrently ridged from nodes 
			ARONIA - red buds, long acute terminal bud, oblong, flattened and appressed. 5 abruptly pointed glandular denticulate scales. Leaf scars u shaped, low. Twigs with solid pith.
			FAGUS - buds long fusiform with scales in 4 rows (decussate), divergent and oblique over leaf scars, >10 scales. Leaf scars half round, small, bundle traces 3. Stipular scars almost encircling twig. Twigs, slender, zig-zag, round.
			POPULUS - buds dimorphic. Terminal buds surrounded by adaxial stipule scales in a spiral. Lateral buds the first bud scale is opposite the principal axis (i.e lowermost bud scale immediately over leaf scar), leaf scar mostly broadly crescent shaped to triangular, twigs rounded, rarely 5 angled.
			AMELANCHIER - buds elongated with half a dozen scales (sometimes more), reddish, acute. Leaf scars narrowly crescent/U shaped. Twigs slender, zig-zag.
			COTINUS	- buds bluish-white with waxy bloom, two valvate bud scales. Leaf scars crescent shaped to 3 lobed. Twigs with yellow wood when scratched, with lenticels, hairless, with waxy bloom too.
			MESPILUS - Buds acute ovoid with >6 bud scales, ciliate. Leaf scars small, dark, crescent shaped and indistinctly 3 traced. Twigs towards the tip densly spreading hairy.
			PYRUS - terminal buds of long shoots are more densly hairy. Basal bud scales of terminal buds acute and keeled. Short shoots with terminal buds. Leaf scars small, blackish. Twigs mostly glabrous.
			MALUS - unsatisfactory at present...
			LABURNUM - bud scales very silver hairy, terminal 3-4mm long. Leaf scar with stipule remains at base, transversely elliptical with 3 bundle traces. Short and long shoots present. Twigs slender, slightly fluted. Pith solid, white.
			LIQUIDAMBAR - buds ovoid, acute with 5-6 bud scales, glossy, reddish with thin ciliate margins. Leaf scars half elliptical, little raised on cushions, with 3 bundle traces. Twigs sometimes with corky ridges, somewhat angled, pith solid, star shaped.
			DAVIDIA - buds acute ovoid, with round base, glossy dark wine red with up to 6 scales. Leaf scars half elliptical to 3 lobed with 3 bundle traces. Twigs hairless, thick, little zig-zag and pith solid with firmer plates at intervals.
			SORBUS - buds variable, sub conical or oblong (globose in torminalis), with terminal buds larger than laterals with inner scales with many hairs and matted with gum, or hairless, bud scales often with a brown margin. Leaf scars with 3 or 5 bundle traces. Leaf cushions different colour to twigs(?).
			The Sorbus species with 3 bundle traces are:
			  Sorbus torminalis - green, glossy bud scales with brown margins, terminal bud blunt (terminal buds 6mm)
			  Sorbus aria (agg) - Woolly buds, green with brown margin (terminal buds 10mm)



1. Pith chambered... *Juglans*
2. Pith not chambered -> 3
    3. Flower buds numerous on elongated racemes (hortal)... *Stachyurus* (praecox)
    4. Flower buds if present, different -> 5
5. Lateral buds short to long stalked -> 7
6. Lateral buds sessile -> 9
    7. Tree. Lateral buds long stalked, with 2(3) valvate scales... *Alnus*
    8. Small shrub. Lateral buds short stalked, with >5 scales... *Ribes*
9. Trunk and boughs of tree with transverse stripes. Buds often collateral... *Prunus*
10. Not as above -> 11
    11. Only short shoots with terminal buds (5-8 scaled), lateral buds 3-5 scaled... *Betula*
    12. Either long shoots or both long and short shoots with terminal buds -> 13
13. Buds clearly dimorphic. Terminal buds: spiral bud scales, lateral buds: distichous scales with lowest above leaf scar... *Populus*
14. Buds similar (terminal buds may be larger), or not as above -> 15
    15. Terminal buds elongated, slender, acute -> 17
    16. Terminal buds less elongate, more squat -> 21
17. Buds divergent, oblique over leaf scars. >10 bud scales exposed... *Fagus*
18. Bud more appressed to twig, <10 bud scales exposed -> 19
    19. 5 or fewer glandular denticulate scales on buds... *Aronia*
    20. >5 scales on buds... *Amelanchier*
21. Bud scales 2, valvate. Twigs pruinose, wood yellow... *Cotinus* (coggyria)
22. Bud scales >2, twigs not pruinose, wood not yellow -> 23
    23. Twigs hairy -> 25
    24. Twigs hairless -> 33
25. Stipules persistent on leaf scar cushion. Buds densly silver hairy... *Laburnum*
26. Stipules not persistent on leaf scar cushion -> 27
    27. Buds with at least some white hairs -> 29
    28. Buds with hairs not white or absent -> 35
29. Bud scales green with brown margin, buds raised on petiole base differently coloured to rest of twig... *Sorbus* 
30. Not as above -> 31
    31. Lateral buds appresssed... *Malus*
    32. Lateral buds spreading -> 33
33. Leaf scars raised equal to bud width, terminal bud larger to 12mm... *Pyrus* and *Malus*
34. Leaf scars raised, > bud width, spreading hirsute to twig apex, terminal bud to 6mm... *Mespilus*
    35. Buds with golden hairs at tip, otherwise brown, acute conical... *Pyrus*
    36. Buds mostly hairless, buds either glossy or sticky ->37
37. Buds shiny dark purple, twigs with indisinct white partitions... *Davidia*    
38. Buds sticky, green to brown. Pith 5 angled, not partitioned... *Liquidambar*



#### Key 5.3.4: Leaf scars with 3 bundle traces, terminal buds absent

      TILIA - bud scales 2(3), mostly green or red glistening. Leaf scars 2 ranked on shoots, stipule scars with one of the pair much elongated, bundle traces 3 or compound and then scattererd. Twigs zig-zag, pith solid.
			BETULA - only short shoots with terminal buds, with 5-8 scales on lateral short shoots and (2)3-5 scales on lateral buds. Leaf scars 2 ranked, half elliptical, small, bundle traces 3, stipule scars narrow. Twigs, slender, zig-zag, round, pith minute, 3 sided, solid.
			CYDONIA - buds with 1-2 exposed bud scales, appressed. Leaf scars small, shallow, u shaped, bundle traces 3, stipule scars small and elongated. Twigs gray woolly, pith small, solid.
			ULMUS - buds solitary, ovoid, oblique to leaf scar, bud scales ~6, 2 ranked. Leaf scars 2 ranked, broadly crescent shaped or half round, bundle traces 3 or in 3 groups, stipule scars unequal. Twigs slender, zig-zag, rounded, pith solid.
			CORYLUS - buds with 4-6 scales, obliquely sessile. Leaf scars 2 ranked anf half round/ triangular, bundle traces 3 or multiplied and obscure. 
			CARPINUS -
			OSTRYA -
			BACCHARIS -
			MYRICA -
			COLUTEA -
			KERRIA -
			SORBARIA -
			PRUNUS -
			RHAMNUS -
			SALIX -
		

#### Key 5.3.5

			GINGKO
			TAXODIUM
			LARIX
			DAPHNE
			RHODODENDRON
			DAPHNE
			ELAEGNUS
			FICUS
			LIRIODENDRON
			MAGNOLIA
			ALNUS
			SORBUS
			FAGUS
			PAEONIA
			QUERCUS
			POTENTILLA


#### Key 5.3.6
   
			NOTHOFAGUS
			TAMARIX
			MORUS
			PLATANUS
			CASTANEA
			TILIA
			AILANTHUS
			GENISTA
			CYTISUS
			TAXODIUM
			SPIRAEA
			HIPPOCREPIS
			COTONEASTER
			POTENTILLA
   
    
    
  
  


Lvs simple
    
    K = Simple, entire, alt (only helpful for evergreen taxa)
    N = Simple, toothed, alt (only helpful for evergreen taxa)
    

TWIGS, PITH, BUDS, LEAF SCARS, BT'S

Olearia - 

KA - paniculata #EVERGREEN - leaves with peltate scales, entire, alternate. Net veined. Unarmed
NC - macrodonta #EVERGREEN - leaves without peltate scales, toothed, alterate. Net veined. Twigs brown, angled. Upturned spine like teeth on leaves 

Eleagnus

KA - umbellata #EVERGREEN
NB, NC - macrophylla

Hippophae

KA - rhamnoides

Quercus

KA - ilex #EVERGREEN
NC, ND, PA - suber, ilex #EVERGREEN
PA - cerris
PA - robus
PA - petraea
PA - rubra
PA - coccinea

Buddleja 

KA - alternifolia

Cotoneaster

KB - many species SOME #EVERGREEN

Frangula

KB - alnus

Salix

KB - many
KF

Photinia

KB - davidiana #EVERGREEN

Cydonia

KB - oblonga

Fagus

KB - sylvatica

Pyrus

KB - salicifolius

Brachyglottis

KB, NC - x jubar #EVERGREEN

Rhododendron

KB - ponticum #EVERGREEN
KB, NF - luteum


Pittosporum

KB - tobira #EVERGREEN
KB - tenuifolium #EVERGREEN
KC - crassifolium #EVERGREEN

Berberis

KB - many sp

Laurus

KB - nobilis #EVERGREEN

Bupleurum

KB - fruticosum #EVERGREEN

Vaccinium 

KB, NF - corymbosum

Cotinus

KB - coggyria

Skimmia

KC - japonica #EVERGREEN

Atriplex

KC - halimus #EVERGREEN

Ilex 

KC, ND - x altaclerensis #EVERGREEN
ND - aquifolium #EVERGREEN


Griselinia

KC - littoralis #EVERGREEN

Tamarix

KC - gallica
KC - africana

Lycium

KC - barbarum
KC - chinense

Berberis

BER - many species SOME #EVERGREEN

Spartium

KC - junceum

Genista 

KC - aetnensis
KC - tenera
KF - tinctoria
KF - hispanica occidentalis
KF - anglica
KF - pilosa

Hedera - 

KD - helix etc

Muehlenbeckia

KD - complexa

Fallopia

KD - baldschuanica

Empetrum

KE - nigrum #EVERGREEN

Ledum

KE - palustre #EVERGREEN

Daboecia

KE - cantabrica #EVERGREEN

Vaccinium

KE - vitis-idaea #EVERGREEN
KE - macrocarpon #EVERGREEN
KE - oxycoccos #EVERGREEN
KE - microcarpon #EVERGREEN
KF - uliginosum

Andromeda 

KE - polifolia #EVERGREEN

Herniaria

KF - ciliolata #EVERGREEN???

Suadea

KF - vera #EVERGREEN

Artemisia

KF - campestris maritima #EVERGREEN??

Sedum

KF - praealtum #EVERGREEN

Daphne

KF - laureola #EVERGREEN
KF - mezereum

Iberis

KF - sempervirens #EVERGREEN

Arctostaphylos 

KF - uva-ursi #EVERGREEN

Diapensia

KF - lapponica #EVERGREEN

############################################################## 
    Lvs toothed
    
Chaenomeles

NA - japonica
NA - speciosa

Berberis

NA - many sp

Ribes

NA, PB - uva-crispa
PB - rubrum
PB - spicatum
PB - alpinus
PB - odoratum
PB - nigrum
PB -sanguineum


Pyracantha

NA - coccinea #EVERGREEN

Rhamnus

NA - cathartica
ND - alaternus

Prunus

NA - spinosa
ND - laurocerasus, lusitanica #EVERGREEN
NF - many sp


Crataegus

NA - mollis
NA - persimilis

Malus 

NA - sylvestris
NF - domestica

Pyrus

NA - communis
NA - pyraster
NA - cordata

Dryas

NB - octopetala #EVERGREEN

Gaultheria

NB, ND - shallon #EVERGREEN
NB - procumbens #EVERGREEN
ND - mucronata

Salix

NB - many sp
NF - many sp

Arctostaphylos

NB - alpinus

Vaccinium 

NB - myrtillus
NB - vitis-idaea #EVERGREEN

Phyllodoce 

NB - caerulea #EVERGREEN

Tilia

NB - petiolaris, tomentosa
NE - many sp
NF - many sp

Populus 

NC - many sp
NF - many sp
PA - many sp

Sorbus

NC - many sp
PA - many sp
PA - torminalis

SD - aucuparia, domestica, cashmiriana, pseudohupehensis

Escallonia #EVERGREEN

ND - macrantha

Arbutus #EVERGREEN

ND - unedo

Leucothoe #EVERGREEN

ND - fontanesiana

Parrotia

NE - persica

Alnus

NE - glutinosa, incana, rubra
NF - cordata

Castanea

NE - sativa

Corylus

NE - avenalla, colurna
PB - avenalla

Betula

NE - many sp

Ulmus

NE - many sp

Carpinus 

NE - betulus

Ostrya

NE - carpinifolia

Kerria

NE - japonica

Fagus

NE - sylvatica

Nothofagus

NE - obliqua, x dodecaphleps, alpina

Amelanchier

NF - lamarckii

Myrica

NF - gale, pensylvanica

Baccharis

NF - halmifolia 

Spiraea

NF - many sp
PB - many sp

Morus

NF - nigra

Mespilus

NF - germanica

Aronia

NF - arbutifolia, melanocarpa

Amelanchier

NF - lamarckii

####

leaves lobed


Lavatera

PA - arborea
PB - x clementii #EVERGREEN

Platanus

PA - x hispanica, orientalis

Trachycarpus 

PA - fortunei #EVERGREEN

Ficus

PA, PB - carica


Liriodendron

PA - tulipifera

Crataegus

PB - monogyna, laevigata

Santolina

PB - chamaecyparissus #EVERGREEN

Rubus

PB - tricolor #EVERGREEN
PB - odoratus
PB - parviflorus

RF - all other brambles
SA - cockburnianus, idaeus


Dryas

PB - octopetala #EVERGREEN

Fatsia

PB - japonica #EVERGREEN

Vitis

PC - vinifera, coignetiae

Parthenocissus

PC - tricuspidata
RH - inserta, quinquefolia


Solanum

PC - dulcamara

Laburnum

RA - anagryoides, x watereri, alpinum

Ulex

see key 2

#########
Leaves compound

Choisya

already keyed

Medicago

RG - arborea

Akebia

RH - quinata

Rosa

SA - many sp

Robinia

SB - pseudoacacia

Juglans

SB, SD - regia


Coronilla

SB - valentina #EVERGREEN

Potentilla

SB - fruticosa

Hippocrepis

SB - emerus

Cotulea

SB - arborescens

Rhus

SD - typina

Pterocarya

SD - fraxinifolia

Ailanthus

SD - altissima

Mahonia

SD - aquifolium, x media #EVERGREEN

Sorbaria

SD - sorbifolia, kirilowii, tomentosa

Aralia

TA - elata

Acacia 

TA - dealbata #EVERGREEN

Lupinus

RE - arborea

Acaena?












Cut text 

17. Bundle traces many (9 or more) in an elliptical, arc shaped or U-shaped series -> 19
18. Bundle traces fewer (7 or less). Buds not superposed. -> 21 
    19. Pith chambered ... *Paulownia* (>3)
    20. Pith not chambered ... *Fraxinus* (>3)
21. Buds naked often behind a persistent petiole base ... *Cornus* (3)
22. Buds with 5-6 scales (thorny?) ... *Rhamnus* (3)

    23. Terminal buds very large, at least 2x as large as laterals, 20mm+. Leaf scars very large, distinct ... *Aesculus* (>3)
    24. Terminal buds not much larger than laterals, or absent -> 25
25. Stipule scars large and obvious ±  1/4 to 1/2 size of leaf scars ... *Staphylea* (3)
26. Stipule scars absent or not obvious -> 27
    27. Buds with a pair of scales meeting in the middle or ± so - buds globose, red ... *Viburnum* (3)
    28. Buds with > 2 scales or buds naked -> 29
29. Terminal buds or all buds naked -> 31
30. All buds with scales -> 35 
    31. Naked buds stellate scurfy ... *Viburnum* (3)
    32. Naked buds not stellate scurfy -> 33
33. Bundle traces 3. Lateral buds >5mm, adpressed, hairy ... *Cornus* (3)
34. Bundle traces >3. Lateral buds minute <2mm ... *Hydrangea* (3, but check all Hydrangeas)





Vegetative key to Quercus species:

Quercus - buds with 5-ranked scales, clustered towards end of twig. Fruits nuts held in a cupule.

1. Leaves evergreen, white to grey woolly below at least when young -> 3
2. Leaves deciduous -> 5
    3. Bark corky, leaves with 5-8 spine tipped teeth ... Quercus suber
    4. Bark not corky, leaves only spined on young shoots ... Quercus ilex
5. Terminal bud cluster with long, narrow, persistent stipules ... Quercus cerris
6. Terminal bud cluster with without long, narrow, persistent stipules -> 7
    7. Leaves lobed with aristate teeth. Hairless except for tufts of orange stellate hairs in vein axils below. Petiole >2.5cm -> 9 
    8. Leaves not toothed with aristate teeth. hairs present or not, but not as above. Petiole <2.5cm -> 11
9. Leaves dull above, lobes < half way to midrib. Hair tufts inconspicuous ... Quercus rubra
10. Leaves shiny above, lobes > half way to midrib. Hair tufts obvious ... Quercus coccinea
    11. Petiole to 1cm. Leaves cordate with reflexed auricles at base. Dull dark green above. Hairless or simple hairs below ... Quercus robur
    12. Petiole >1cm. Leaves cuneate, auricles absent. Shiny dark green above. Hairs stellate below ... Quercus petraea
    
Glossary:
Stipules - small herbaceous organs at base of buds or petiole
Stellate - star shaped
Aristate - with an awn or bristle
Cordate - heart shaped, with base rounded
Auricules - small lobed appendage
Cuneate - tapered to a base
